### PR TITLE
Added Helvetica Neue font; replaces Tahoma

### PR DESCRIPTION
**Pull request by jimkrill**
Replaced "Tahoma" fonts with Helvetica, pulled from fonts.com.

Questions:
- Should we pull this remote stylesheet / fonts from font.com; or should we host them locally?  
- Are they already hosted locally, and if so - what is the URL to the fonts / stylesheet?

### CODE REVIEW

**Comment by jimkrill** [comment]
questions_and_answers_ _marklogic_developer_community

**Comment by jimkrill** [comment]
Do we want this Stackoverflow section using Helvetica as well - or stay Arial?

It's located in /src/stackunderflow/stackoverflow.css and stackoverflow.min.css

**Comment by dmcassel** [comment]
Looks like using font.com/font.net requires a membership. I'm good with us hosting some font files. We have a src/fonts/ directory, but that just has glyphicons right now. No preference on font choice for Stackoverflow, I'll defer to Steve on that one.

**Comment by jimkrill** [comment]
meet_ _marklogic_developer_community

Verdana on Meetup code is being applied from inline <style> tag.  Couldn't find this code in /src/ so I'm assuming it's coming from the db. yes?

@dmcassel do you know how to access this data?

**Comment by dmcassel** [comment]
@jimkrill, we load the user group with this: 

    <script src="http://www.meetup.com/embed/map/marklogic/" type="text/javascript" xml:space="preserve"/>

Stick that URL in a browser and you'll see what we get back. It includes the Verdana font. Doesn't look like we have control over that.

**Comment by jimkrill** [comment]
There may be settings within meetup.com where you can specificy the font. Who would have access to that account?

**Comment by dmcassel** [comment]
Good question, I'll have to look into that. 

Other than that, what's the state of this PR? Make sense to accept it?

**Comment by jimkrill** [comment]
Yeah, I mean the font gets changed everywhere else and is now being loaded locally instead of remotely.

**Pull request closed without merging**
