### PR TITLE
Update document-list.xml

### PR DESCRIPTION
**Pull request by gfurbush**
Add OpsDirector to nightly doc builds

### CODE REVIEW

**Comment by dmcassel** [comment]
Looks good to me

**Comment by gfurbush** [comment]
What’s my next move?  How do I get the changes into github?

**Comment by dmcassel** [comment]
I've accept your Pull Request, which gets your change into the master branch.

**Comment by kcoleman-marklogic** [comment]
I don't believe this belongs on master right now. This is unreleased content for Ops Director, aimed at 9.0-2. The right thing to do is check the change into the docapp branch ONLY. No pull request is required for that. You can just do it.

Danny's wiki page on "RunDMC for the Docs Team" has a section on "Making Changes to RunDMC" that should be the directions you're seeking, Gordon.

**Comment by gfurbush** [comment]
Yeah, I just learned that.  Updated docapp and requested a pull

**Comment by dmcassel** [comment]
Crud. Okay, I'll back the change out of master.

**Pull request merged**
