### PR TITLE
Update document-list.xml

### PR DESCRIPTION
**Pull request by gfurbush**
Added Ops Dir guide

### CODE REVIEW

**Comment by dmcassel** [comment]
For docs-related stuff, ideally someone from the docs team should review and accept the PR. @kcoleman-marklogic?

**Comment by gfurbush** [comment]
I don’t have permission.

**Comment by kcoleman-marklogic** [comment]
The change is fine, just on the wrong branch. I am a bit confused about the state of things at this point, so IDK what I'm approving.  We "just" need to revert the merge to master, and then Gordon can make the equivalent change directly on the docapp branch.

**Comment by gfurbush** [comment]
I’ve already made the change on docapp, but I don’t have permissions to save it into github.

**Pull request merged**
